=== sebthom/oval/tags/1.32/src/misc/findbugs-filter.dtd
<!-- 

<!DOCTYPE FindBugsFilter SYSTEM "findbugs-filter.dtd">

-->

<!-- generated with http://www.hitsw.com/xml_utilites/ -->

<!ELEMENT Bug EMPTY >
<!ATTLIST Bug code CDATA #IMPLIED >
<!ATTLIST Bug pattern CDATA #IMPLIED >

<!ELEMENT Class EMPTY >
<!ATTLIST Class name NMTOKEN #REQUIRED >

<!ELEMENT FindBugsFilter ( Match+ ) >

<!ELEMENT Match ( Bug | Or | Method | Class | Package | Priority )* >

<!ELEMENT Method EMPTY >
<!ATTLIST Method name CDATA #REQUIRED >
<!ATTLIST Method params CDATA #IMPLIED >
<!ATTLIST Method returns NMTOKEN #IMPLIED >

<!ELEMENT Or ( Class | Method | Package )* >

<!ELEMENT Package EMPTY >
<!ATTLIST Package name NMTOKEN #REQUIRED >

<!ELEMENT Priority EMPTY >
<!ATTLIST Priority value NMTOKEN #REQUIRED >

=== sebthom/oval/tags/1.30/src/misc/findbugs-exclude.xml
<!-- this fails with the findbugs plugin <!DOCTYPE FindBugsFilter SYSTEM "findbugs-filter.dtd"> -->

<!DOCTYPE FindBugsFilter PUBLIC "-//FindBugs/FindBugs Filter Configuration DTD 1.0//EN" "http://oval.sourceforge.net/misc/findbugs-filter.dtd">

<FindBugsFilter>
	<Match>
		<Class name="net.sf.oval.constrain.ValidateWithMethodCheck" />
		<Bug pattern="REC_CATCH_EXCEPTION" />
	</Match>
	<Match>
		<Or>
			<Class name="net.sf.oval.AbstractCheck" />
			<Class name="net.sf.oval.AbstractCheckExclusion" />
			<Class name="net.sf.oval.ConstraintViolation" />
			<Class name="net.sf.oval.constraint.InstanceOfAnyCheck" />
			<Class name="net.sf.oval.constraint.InstanceOfCheck" />
			<Class name="net.sf.oval.exception.ConstraintsViolatedException" />
			<Class name="net.sf.oval.internal.util.SerializableConstructor" />
			<Class name="net.sf.oval.internal.util.SerializableMethod" />
		</Or>
		<Bug code="EI,EI2" />
	</Match>
	<Match>
		<Or>
			<Package name="net.sf.oval.test.constraints" />
			<Package name="net.sf.oval.test.guard" />
			<Package name="net.sf.oval.test.validator" />
		</Or>
		<Bug
			pattern="MF_CLASS_MASKS_FIELD,HE_EQUALS_USE_HASHCODE,ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD,UUF_UNUSED_FIELD,HE_HASHCODE_USE_OBJECT_EQUALS,URF_UNREAD_FIELD,SIC_INNER_SHOULD_BE_STATIC_ANON" />
	</Match>
	<Match>
		<Package name="net.sf.oval.constraint" />
		<Bug pattern="SE_TRANSIENT_FIELD_NOT_RESTORED" />
	</Match>
	
	<Match>
		<!-- AspectJ code -->
		<Method name="~^ajc\$pointcut\$\$.*$" />
		<Bug pattern="UPM_UNCALLED_PRIVATE_METHOD" />
	</Match>
	
	<Match>
		<!-- AspectJ code -->
		<Method name="~^init\$_aroundBody\d+\$advice.*$" />
		<Bug pattern="DLS_DEAD_LOCAL_STORE" />
	</Match>
	 
     <!-- Match all XYZ violations. -->
	<Match>
		<Bug pattern="UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR" />
	</Match>
</FindBugsFilter>
