=== sebthom/oval/tags/oval-1.40/src/misc/xml-schemas/oval-configuration-0.8.dtd
<!-- OVal DTD

<!DOCTYPE oval PUBLIC 
   "-//OVal/OVal Configuration DTD 0.8//EN"
   "http://oval.sourceforge.net/oval-configuration-0.8.dtd">

  http://en.wikipedia.org/wiki/Document_Type_Definition
-->

<!-- the root element -->
<!ELEMENT oval ( (constraintSet*|class*)* ) >

<!-- constraint set configuration elements -->
<!ELEMENT constraintSet ANY >
<!ATTLIST constraintSet id NMTOKEN #REQUIRED >
<!ATTLIST constraintSet overwrite NMTOKEN #IMPLIED >

<!-- class configuration elements -->
<!ELEMENT class ( (field*|constructor*|method*)* ) >
<!ATTLIST class applyFieldConstraintsToSetter NMTOKEN #IMPLIED >
<!ATTLIST class overwrite NMTOKEN #IMPLIED >
<!ATTLIST class type CDATA #REQUIRED >

<!-- validation context elements -->
<!ELEMENT field ANY >
<!ATTLIST field defineConstraintSet NMTOKEN #IMPLIED >
<!ATTLIST field name NMTOKEN #REQUIRED >
<!ATTLIST field overwrite NMTOKEN #IMPLIED >

<!ELEMENT constructor ( parameter+ ) >
<!ATTLIST constructor overwrite NMTOKEN #IMPLIED >

<!ELEMENT method (parameter*,returnValue?) >
<!ATTLIST method name NMTOKEN #REQUIRED >
<!ATTLIST method overwrite NMTOKEN #IMPLIED >

<!ELEMENT parameter ANY >
<!ATTLIST parameter overwrite NMTOKEN #IMPLIED >
<!ATTLIST parameter type NMTOKEN #REQUIRED >

<!ELEMENT returnValue ANY >
<!ATTLIST returnValue overwrite NMTOKEN #IMPLIED >

<!-- built-in constraints -->
<!ELEMENT net.sf.oval.constraints.AssertConstraintSetCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.AssertConstraintSetCheck id NMTOKEN #REQUIRED >
<!ATTLIST net.sf.oval.constraints.AssertConstraintSetCheck message CDATA #IMPLIED >
<!ATTLIST net.sf.oval.constraints.AssertConstraintSetCheck source NMTOKEN #IMPLIED >

<!ELEMENT net.sf.oval.constraints.AssertFalseCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.AssertFalseCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.AssertFieldConstraintsCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.AssertFieldConstraintsCheck fieldName NMTOKEN #REQUIRED >
<!ATTLIST net.sf.oval.constraints.AssertFieldConstraintsCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.AssertTrueCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.AssertTrueCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.AssertValidCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.AssertValidCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.InstanceOfCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.InstanceOfCheck clazz NMTOKEN #REQUIRED >
<!ATTLIST net.sf.oval.constraints.InstanceOfCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.LengthCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.LengthCheck max NMTOKEN #IMPLIED >
<!ATTLIST net.sf.oval.constraints.LengthCheck message CDATA #IMPLIED >
<!ATTLIST net.sf.oval.constraints.LengthCheck min NMTOKEN #IMPLIED >

<!ELEMENT net.sf.oval.constraints.NotEmptyCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.NotEmptyCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.NotNegativeCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.NotNegativeCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.NotNullCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.NotNullCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.NotSelfRefCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.NotSelfRefCheck message CDATA #IMPLIED >

<!ELEMENT net.sf.oval.constraints.RangeCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.RangeCheck max NMTOKEN #IMPLIED >
<!ATTLIST net.sf.oval.constraints.RangeCheck message CDATA #IMPLIED >
<!ATTLIST net.sf.oval.constraints.RangeCheck min NMTOKEN #IMPLIED >

<!ELEMENT net.sf.oval.constraints.RegExCheck ( pattern ) >
<!ATTLIST net.sf.oval.constraints.RegExCheck message CDATA #IMPLIED >

<!ELEMENT pattern EMPTY >
<!ATTLIST pattern flags NMTOKEN #IMPLIED >
<!ATTLIST pattern pattern CDATA #REQUIRED >

<!ELEMENT net.sf.oval.constraints.SizeCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.SizeCheck max NMTOKEN #IMPLIED >
<!ATTLIST net.sf.oval.constraints.SizeCheck message CDATA #IMPLIED >
<!ATTLIST net.sf.oval.constraints.SizeCheck min NMTOKEN #IMPLIED >

<!ELEMENT net.sf.oval.constraints.ValidateWithMethodCheck EMPTY >
<!ATTLIST net.sf.oval.constraints.ValidateWithMethodCheck ignoreIfNull NMTOKEN #IMPLIED >
<!ATTLIST net.sf.oval.constraints.ValidateWithMethodCheck message CDATA #IMPLIED >
<!ATTLIST net.sf.oval.constraints.ValidateWithMethodCheck methodName NMTOKEN #REQUIRED >
<!ATTLIST net.sf.oval.constraints.ValidateWithMethodCheck parameterType NMTOKEN #REQUIRED >

=== sebthom/oval/net.sf.oval/src-test/net/sf/oval/test/enforcer/XMLConfigurationTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE oval PUBLIC 
   "-//OVal/OVal Configuration DTD 0.8//EN"
   "http://oval.sourceforge.net/oval-configuration-0.8.dtd">
<oval>
	<!-- define a constraint set -->
	<constraintSet id="user.userid">
		<net.sf.oval.constraints.NotNullCheck message="{0} is null" />
		<net.sf.oval.constraints.RegExCheck message="{0} does not match the pattern {2}">
			<pattern pattern="^[a-z0-9]{8}$" flags="0" />
		</net.sf.oval.constraints.RegExCheck>
	</constraintSet>

	<!-- define checks for the net.sf.oval.test.enforcer.XMLConfigurationTest$User class -->
	<!-- overwrite=false means already defined checks for this class will not be removed -->
	<class type="net.sf.oval.test.enforcer.XMLConfigurationTest$User" overwrite="false"
		applyFieldConstraintsToSetter="true">
		<field name="firstName">
			<net.sf.oval.constraints.LengthCheck min="0" max="3"
				message="{0} is not between {2} and {3} characters long" />
		</field>

		<field name="lastName">
			<net.sf.oval.constraints.LengthCheck min="0" max="5"
				message="{0} is not between {2} and {3} characters long" />
		</field>

		<!-- overwrite=true means previously defined checks for this field will be overwritten by the checks defined here -->
		<field name="userId" overwrite="true">
			<!-- use the checks defined for the constaint set "user.userid" -->
			<net.sf.oval.constraints.AssertConstraintSetCheck id="user.userid" />
		</field>

		<!-- define constructor parameter checks -->
		<constructor>
			<!-- parameter 1 -->
			<parameter type="java.lang.String">
				<net.sf.oval.constraints.AssertConstraintSetCheck id="user.userid" />
			</parameter>

			<!-- parameter 2 -->
			<parameter type="java.lang.String">
				<net.sf.oval.constraints.AssertConstraintSetCheck id="user.userid" />
			</parameter>

			<!-- parameter 3 -->
			<!-- the types of all parameters must be listed, even if no checks are defined -->
			<parameter type="int" />
		</constructor>

		<!-- define a getter return value check -->
		<method name="getManagerId">
			<!-- returnValue -  use the checks defined for the constaint set "user.userid" -->
			<returnValue>
				<net.sf.oval.constraints.AssertConstraintSetCheck id="user.userid" />
			</returnValue>
		</method>

		<!-- define method parameter checks -->
		<method name="setManagerId">
			<!-- parameter 1 -->
			<parameter type="java.lang.String">
				<net.sf.oval.constraints.AssertConstraintSetCheck id="user.userid" />
			</parameter>
		</method>
	</class>
</oval>
